### ISSUE TITLE
CrudMaker : fail to use relationships option to make many to many relations

### ISSUE THREAD

**Issue by claborier** [GrafiteInc/Builder#157]
Hi !

First, thanks for your great work, I've been searching for a solution like LaraCogs for months :)

However I encounter a problem using the crudmaker to create many to many relations. 

I've posted a question on Laracast where I describe the problem, here it is : 
https://laracasts.com/discuss/channels/laravel/how-to-use-laracogs-crudmaker-relationships-option-to-create-relationnal-table

I'm not sure to use the crudmaker as it should be... or maybe I'm expected some magic that it isn't capable to do ? 

Can you help me with that ? 

Thanks

**Comment by mlantz** [comment]
Check out my comments on LaraCasts I'll be addressing it this weekend. Thanks for posting.

**Comment by rccursach** [comment]
@mlantz link?

**Comment by mlantz** [comment]
https://laracasts.com/discuss/channels/laravel/how-to-use-laracogs-crudmaker-relationships-option-to-create-relationnal-table @rccursach
