### ISSUE TITLE
Fail to retrieve Activitity by user

### ISSUE THREAD

**Issue by jackleblack-kpt** [GrafiteInc/Builder#190]
Thanks for this amazing work .

I have a problem with the Activity service, when I use Activity::getByUser(1) : 
> Unknown column 'user' in 'where clause' (SQL: select * from `activities` where `user` = 1) 

This fix solve the error, line 23 from ActivityService : 
> $this->model->where('**user**',$userId);  => $this->model->where('**user_id**', $userId);

**Comment by mlantz** [comment]
Awesome thanks, I'll push the fix ASAP
