### ISSUE TITLE
How to provide token when adding records via AJAX? {"error":"token_not_provided"}

### ISSUE THREAD

**Issue by connor11528** [GrafiteInc/Builder#194]
I created an app with the Grafite API builder and then used the CRUD generator for an Activity model. Instead of the jQuery on the frontend I am using Vue.js. I'd like to have a form for a User to add an Activity. A user needs to be registered and signed in to create an activity.

How do I get the JWT token to pass to the backend to prove that the user is logged in?

**addActivityForm.vue**
```
<template>
    <div id="add-activity">
        Activity date:
        <datepicker @date-updated="setActivityDate" v-once></datepicker>
        Activity name: <input type="text" v-model="activity.name" class="form-control">
        <div class="btn btn-primary" @click="submitActivity()">Add activity</div>
    </div>
</template>

<script>
	import moment from 'moment';
    import axios from 'axios';

	export default {
		data() {
			return {
				activity: { date: moment().format('L'), name: null },
			}
		},
		methods: {
			setActivityDate(date) {
				this.activity.date = date;
			},
			submitActivity() {
				axios.post('/api/v1/activities', this.activity, {
					headers: {Authorization: "Bearer " + _token}
				})
                                 .then((res) => { console.log(res); })
                                 .catch((err) => { console.error(err); })
          
			}
		}
	}
</script>
```

The response to this request is: 

```
{"error":"token_not_provided"}
```

The **ActivitiesController** method for storing an Activity:

```
    /**
     * Store a newly created resource in storage.
     *
     * @param  App\Http\Requests\ActivityCreateRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ActivityCreateRequest $request)
    {
        $result = $this->service->create($request->except('_token'));

        if ($result) {
            return response()->json($result);
        }

        return response()->json(['error' => 'Unable to create activity'], 500);
    }
```

And the **ActivityCreateRequest**:

```
<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use App\Models\Activity;

class ActivityCreateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        if (auth()->user()) {
            return true;
        }

        return false;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return Activity::$rules;
    }
}
```

The registering, logging in and email validation all works like a charm (thanks for that). My question is what do I need to pass in the AJAX request in order to create an Activity?

**Comment by mlantz** [comment]
To do an AJAX request with the user already logged in you dont need JWT. JWT is designed for apps that have a completely separated front-end to backend example: Single Page Applications that need to authenticate with an API. Ember is a great JavaScript framework for that.

Based on what I'm seeing you're trying to send the `_token` as an Authorization header. If you're using the `_token` that is defined by default thats the CSRF token so you need to adjust your request as follows:

```<input type="hidden" v-model="activity._token" value="window._token">```

```submitActivity() {
				axios.post('/api/v1/activities', this.activity)
                                 .then((res) => { console.log(res); })
                                 .catch((err) => { console.error(err); })
          
			}```

Then in the `master.blade.php` file you'll need to adjust the `_token` to `window._token` that should work then.

**Comment by connor11528** [comment]
Okay thank you for the explanation of using JWT. I think it's going to be easier to use the CRUD Maker pattern and similar type forms.

I spun up a new Grafite app to test the CRUD Maker and ran into an issue where in ActivateService:sendActivationToken `auth()->user()->meta` is evaluating to null, even after I ran the seeder.

Do you know why the meta relationship comes up null after running the seeder? (If this is better as a separate issue I can open it that way)

**Comment by mlantz** [comment]
Off the top of my head no, you'd have to check your database and confirm that that relationship exists.

**Comment by connor11528** [comment]
All good! Appreciate the help. I'm simplifying it by adding activities the old fashion way:

```
<form method="POST" action="/activities">
    {{ csrf_field() }}
    <input type="date" class="form-control" name="date">
    <input type="text" class="form-control" name="title">
    <input type="submit" value="Add Activity" class="btn btn-primary">
</form>
```

Down the line I'll get more comfortable with API interactions and the CRUD Maker. Awesome tool!
