### ISSUE TITLE
Missing lines from LogsController.php

### ISSUE THREAD

**Issue by AkkuFresh** [GrafiteInc/Builder#197]
Hello,
First of all, many thanks for the great job done with the Builder.

I have just tried the functions and to list the application logs with Builder by instruction from here:
[https://docs.grafite.ca/builder/logs/](https://docs.grafite.ca/builder/logs/)
I had found an issue.
Going through the install steps and running the app in the rout /admin/logs
There was an error:
Undefined variable: dates (View: ...\laravel\resources\views\admin\logs\index.blade.php) {"userId":1,"email":"admin@example.com","exception":"[object] (ErrorException(code: 0)}

Looking inside it, the LogsController@index not defined the variable date passed to the view:
Adding the lines listed here, the issue was handled.
Define $dates: **$dates = $this->service->getLogDates();**
Pass to the view: **->with('dates', $dates)**

```
    public function index(Request $request)
    {
        $logs = $this->service->get($request->all());
        $levels = $this->service->levels;
        $dates = $this->service->getLogDates();

        return view('admin.logs.index')
            ->with('dates', $dates)
            ->with('logs', $logs)
            ->with('levels', $levels);
    }
```

**Comment by mlantz** [comment]
Hey thanks! that's clearly a blunder on my part, I'll push the fix shortly. Thanks for the feedback :)

**Comment by mlantz** [comment]
Corrected in the latest release - thanks!
