### ISSUE TITLE
MySQL specific query on Blade template, it will fail with other DB engine

### ISSUE THREAD

**Issue by brBart** [GrafiteInc/Builder#198]
**Describe the bug**
This is a MySQL specific query on Blade template, it will fail with other DB engine
https://github.com/GrafiteInc/Builder/blob/356ebdcbc6b5d99769696c94e3a8e56652913c2a/src/Packages/Bootstrap/resources/views/admin/dashboard.blade.php#L60

**To Reproduce**
use any other DB e.g. SQLite on unit tests

**Comment by mlantz** [comment]
Since the dashboard is published to your application and you can modify it as you see fit, feel free to remove this. Any updates in the future will not affect this.
