### ISSUE TITLE
DB::select('SHOW VARIABLES ...') in /admin/dashboard.blade.php not postgres compatible

### ISSUE THREAD

**Issue by benjaminboruff** [GrafiteInc/Builder#199]
For `grafite:bootstrap` the generated admin dashboard view (`/resources/views/admin/dashboard.blade.php`) contains

```
@foreach (DB::select('SHOW VARIABLES LIKE "%version%";') as $dbVar)
     <tr>
          <td>{{ ucfirst(str_replace('_', ' ', $dbVar->Variable_name)) }}</td>
          <td class="text-right">{{ $dbVar->Value }}</td>
     </tr>
@endforeach
```

... but it causes an error when being routed there after logging in as admin - using **postgres 10.5**.

`SHOW VARIABLES` doesn't work in the `psql` shell, either. I removed the code from the view and the page loads without error.

* PHP 7.2.9-1+ubuntu16.04.1+deb.sury.org+1
* Laravel Framework 5.7.6

**Comment by benjaminboruff** [comment]
Sorry, just saw the other closed issue just like this! Closing ....

**Comment by mlantz** [comment]
As a side note, technically I think most of Builder's stuff along with the CMS will work fine with PostGres but its not optimized for it
